package com.fuso.enterprise.ots.srv.api.service.functional;

import java.util.List;

import org.json.JSONException;
import org.json.JSONObject;

import com.fuso.enterprise.ots.srv.api.model.domain.CompleteOrderDetails;
import com.fuso.enterprise.ots.srv.api.model.domain.DonationResponseByStatus;
import com.fuso.enterprise.ots.srv.api.model.domain.OrderDetails;
import com.fuso.enterprise.ots.srv.api.model.domain.OrderProductDetails;
import com.fuso.enterprise.ots.srv.api.model.domain.SchedulerResponceOrderModel;
import com.fuso.enterprise.ots.srv.api.service.request.AddDonationtoRequest;
import com.fuso.enterprise.ots.srv.api.service.request.AddOrUpdateOnlyOrderProductRequest;
import com.fuso.enterprise.ots.srv.api.service.request.AddOrUpdateOrderProductBOrequest;
import com.fuso.enterprise.ots.srv.api.service.request.AddSchedulerRequest;
import com.fuso.enterprise.ots.srv.api.service.request.CloseOrderBORequest;
import com.fuso.enterprise.ots.srv.api.service.request.DirectSalesVoucherRequest;
import com.fuso.enterprise.ots.srv.api.service.request.EmployeeOrderTransferRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetAssginedOrderBORequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetCustomerOrderByStatusBOrequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetDonationByStatusRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetDonationReportByDateRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetListOfOrderByDateBORequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetOrderBORequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetOrderByStatusRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetOrderForFacilitatorRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetSchedulerRequest;
import com.fuso.enterprise.ots.srv.api.service.request.GetUserDetailsForRequest;
import com.fuso.enterprise.ots.srv.api.service.request.OrderIdBORequest;
import com.fuso.enterprise.ots.srv.api.service.request.SaleVocherBoRequest;
import com.fuso.enterprise.ots.srv.api.service.request.UpdateDonationRequest;
import com.fuso.enterprise.ots.srv.api.service.request.UpdateForAssgineBOrequest;
import com.fuso.enterprise.ots.srv.api.service.request.UpdateOrderDetailsRequest;
import com.fuso.enterprise.ots.srv.api.service.request.UpdateOrderStatusRequest;
import com.fuso.enterprise.ots.srv.api.service.request.UpdateOrderdProductRequest;
import com.fuso.enterprise.ots.srv.api.service.response.GetDonationReportByDateResponse;
import com.fuso.enterprise.ots.srv.api.service.response.GetListOfOrderByDateBOResponse;
import com.fuso.enterprise.ots.srv.api.service.response.GetSchedulerResponse;
import com.fuso.enterprise.ots.srv.api.service.response.GetUserDetailsForResponse;
import com.fuso.enterprise.ots.srv.api.service.response.OrderDetailsBOResponse;
import com.fuso.enterprise.ots.srv.api.service.response.OrderProductBOResponse;
import com.razorpay.Payment;

public interface OTSOrderService {
	OrderDetailsBOResponse getOrderBydate(GetOrderBORequest getOrderBORequest);
	OrderProductBOResponse getOrderByStatusAndDistributor(GetOrderByStatusRequest getOrderByStatusRequest);
	OrderProductBOResponse insertOrderAndProduct(AddOrUpdateOrderProductBOrequest addOrUpdateOrderProductBOrequest);
	String addOrUpdateOrderProduct(AddOrUpdateOnlyOrderProductRequest AddOrUpdateOnlyOrderProductRequest); 
	String UpdateOrder(UpdateOrderDetailsRequest updateOrderDetailsRequest);
	String updateAssginedOrder(UpdateForAssgineBOrequest  updateForAssgineBOrequest);
	OrderProductBOResponse getAssginedOrder(GetAssginedOrderBORequest getAssginedOrderBORequest);
	String closeOrder(CloseOrderBORequest closeOrderBORequest);
	OrderProductBOResponse getCustomerOrderStatus(GetCustomerOrderByStatusBOrequest getCustomerOrderByStatusBOrequest);
	OrderProductBOResponse getOrderDetailsByDate(GetOrderBORequest getOrderBORequest);
	GetListOfOrderByDateBOResponse getListOfOrderByDate(GetListOfOrderByDateBORequest getListOfOrderByDateBORequest);
	String SalesVocher(SaleVocherBoRequest saleVocherBoRequest);
	OrderProductBOResponse orderReportByDate(GetOrderBORequest getOrderBORequest);
	String InsertScheduler(AddSchedulerRequest  addSchedulerRequest);
	GetSchedulerResponse getScheduler(GetSchedulerRequest getSchedulerRequest);
	String employeeTransferOrder(EmployeeOrderTransferRequest employeeOrderTransferRequest);
	String runScheduler12AMTO1AM();
	String UpdateOrderStatus(UpdateOrderStatusRequest updateOrderStatusRequest);
	String schedulerOrder(AddOrUpdateOrderProductBOrequest addOrUpdateOrderProductBOrequest);
	String directSalesVoucher(DirectSalesVoucherRequest directSalesVoucherRequest);
	String insertOrderAndProductFordirectSalesVoucher(
			AddOrUpdateOrderProductBOrequest addOrUpdateOrderProductBOrequest);
	OrderProductBOResponse getOrderDiruectSalesVoucher(String orderId);
	DonationResponseByStatus getDonationListBystatus(GetDonationByStatusRequest donationByStatusRequest);
	String addNewDonation(AddDonationtoRequest addDonationtoRequest);
	GetDonationReportByDateResponse getDonationReportByDate(GetDonationReportByDateRequest donationReportByDateRequest);
	GetUserDetailsForResponse getListOfOrderDetailsForRequest(GetUserDetailsForRequest getUserDetailsForRequest);
	GetDonationReportByDateResponse getDonationForUpdateStatus(GetDonationByStatusRequest donationByStatusRequest);
	String updateDonation(UpdateDonationRequest updateDonationRequest);
	String donateDonation(SaleVocherBoRequest saleVocherBoRequest);
	OrderDetailsBOResponse getRazorPayOrder(UpdateOrderDetailsRequest updateOrderDetailsRequest) throws JSONException;
	JSONObject fetchPaymentDetailsByPaymetId(String paymentId);
	OrderDetails getOrderDetailsForOrderId(OrderIdBORequest updateOrderDetailsRequest);
	List<OrderProductDetails> getUserByStatuesAndDistributorId(GetOrderForFacilitatorRequest  getOrderForFacilitatorRequest);
	String updateOrderdProductStatus(UpdateOrderdProductRequest updateOrderdProductRequest);
}
